<?php
require_once('sql/Connection.class.php');
require_once('sql/ConnectionFactory.class.php');
require_once('sql/ConnectionProperty.class.php');
require_once('sql/QueryExecutor.class.php');
require_once('sql/Transaction.class.php');
require_once('sql/SqlQuery.class.php');
require_once('core/ArrayList.class.php');

/**
 * Generated by DAOFactory - Codeigniter edition
 * @author: Alwyn Wymeersch
 * @date: ${date}
 */

class DAOFactory extends CI_Model {
    public function __construct() {
        $this->load->database();

        define('DB_HOST', $this->db->hostname);
        define('DB_NAME', $this->db->database);
        define('DB_USER', $this->db->username);
        define('DB_PASS', $this->db->password);
    }

    public function load($tablename) {
        require_once('dao/' . $this->getClazzName($tablename) . 'DAO.class.php');
        require_once('dto/' . $this->getClazzName($tablename) . 'Dto.class.php');
        require_once('mysql/' . $this->getClazzName($tablename) . 'MySqlDAO.class.php');
        require_once('mysql/ext/' . $this->getClazzName($tablename) . 'MySqlExtDAO.class.php');
    }

    public function loadAll($tablenames) {
        foreach ($tablenames as $key => $tablename) {
            $this->load($tablename);
        }
    }

    /**
     * @return BulanMySqlExtDAO
     */
    public function getBulanDAO() {
        return new BulanMySqlExtDAO();
    }

    /**
     * @return CbtBankSoalMySqlExtDAO
     */
    public function getCbtBankSoalDAO() {
        return new CbtBankSoalMySqlExtDAO();
    }

    /**
     * @return CbtDurasiSiswaMySqlExtDAO
     */
    public function getCbtDurasiSiswaDAO() {
        return new CbtDurasiSiswaMySqlExtDAO();
    }

    /**
     * @return CbtJadwalMySqlExtDAO
     */
    public function getCbtJadwalDAO() {
        return new CbtJadwalMySqlExtDAO();
    }

    /**
     * @return CbtJawabanMySqlExtDAO
     */
    public function getCbtJawabanDAO() {
        return new CbtJawabanMySqlExtDAO();
    }

    /**
     * @return CbtJenisMySqlExtDAO
     */
    public function getCbtJenisDAO() {
        return new CbtJenisMySqlExtDAO();
    }

    /**
     * @return CbtKelasRuangMySqlExtDAO
     */
    public function getCbtKelasRuangDAO() {
        return new CbtKelasRuangMySqlExtDAO();
    }

    /**
     * @return CbtKopAbsensiMySqlExtDAO
     */
    public function getCbtKopAbsensiDAO() {
        return new CbtKopAbsensiMySqlExtDAO();
    }

    /**
     * @return CbtKopBeritaMySqlExtDAO
     */
    public function getCbtKopBeritaDAO() {
        return new CbtKopBeritaMySqlExtDAO();
    }

    /**
     * @return CbtKopKartuMySqlExtDAO
     */
    public function getCbtKopKartuDAO() {
        return new CbtKopKartuMySqlExtDAO();
    }

    /**
     * @return CbtNilaiMySqlExtDAO
     */
    public function getCbtNilaiDAO() {
        return new CbtNilaiMySqlExtDAO();
    }

    /**
     * @return CbtNomorPesertaMySqlExtDAO
     */
    public function getCbtNomorPesertaDAO() {
        return new CbtNomorPesertaMySqlExtDAO();
    }

    /**
     * @return CbtPengawasMySqlExtDAO
     */
    public function getCbtPengawasDAO() {
        return new CbtPengawasMySqlExtDAO();
    }

    /**
     * @return CbtRekapMySqlExtDAO
     */
    public function getCbtRekapDAO() {
        return new CbtRekapMySqlExtDAO();
    }

    /**
     * @return CbtRuangMySqlExtDAO
     */
    public function getCbtRuangDAO() {
        return new CbtRuangMySqlExtDAO();
    }

    /**
     * @return CbtSesiMySqlExtDAO
     */
    public function getCbtSesiDAO() {
        return new CbtSesiMySqlExtDAO();
    }

    /**
     * @return CbtSesiSiswaMySqlExtDAO
     */
    public function getCbtSesiSiswaDAO() {
        return new CbtSesiSiswaMySqlExtDAO();
    }

    /**
     * @return CbtSoalMySqlExtDAO
     */
    public function getCbtSoalDAO() {
        return new CbtSoalMySqlExtDAO();
    }

    /**
     * @return CbtSoalSiswaMySqlExtDAO
     */
    public function getCbtSoalSiswaDAO() {
        return new CbtSoalSiswaMySqlExtDAO();
    }

    /**
     * @return GroupsMySqlExtDAO
     */
    public function getGroupsDAO() {
        return new GroupsMySqlExtDAO();
    }

    /**
     * @return HariMySqlExtDAO
     */
    public function getHariDAO() {
        return new HariMySqlExtDAO();
    }

    /**
     * @return JabatanGuruMySqlExtDAO
     */
    public function getJabatanGuruDAO() {
        return new JabatanGuruMySqlExtDAO();
    }

    /**
     * @return KelasCatatanMapelMySqlExtDAO
     */
    public function getKelasCatatanMapelDAO() {
        return new KelasCatatanMapelMySqlExtDAO();
    }

    /**
     * @return KelasCatatanWaliMySqlExtDAO
     */
    public function getKelasCatatanWaliDAO() {
        return new KelasCatatanWaliMySqlExtDAO();
    }

    /**
     * @return KelasEkstraMySqlExtDAO
     */
    public function getKelasEkstraDAO() {
        return new KelasEkstraMySqlExtDAO();
    }

    /**
     * @return KelasJadwalKbmMySqlExtDAO
     */
    public function getKelasJadwalKbmDAO() {
        return new KelasJadwalKbmMySqlExtDAO();
    }

    /**
     * @return KelasJadwalMapelMySqlExtDAO
     */
    public function getKelasJadwalMapelDAO() {
        return new KelasJadwalMapelMySqlExtDAO();
    }

    /**
     * @return KelasJadwalMateriMySqlExtDAO
     */
    public function getKelasJadwalMateriDAO() {
        return new KelasJadwalMateriMySqlExtDAO();
    }

    /**
     * @return KelasJadwalTugasMySqlExtDAO
     */
    public function getKelasJadwalTugasDAO() {
        return new KelasJadwalTugasMySqlExtDAO();
    }

    /**
     * @return KelasMateriMySqlExtDAO
     */
    public function getKelasMateriDAO() {
        return new KelasMateriMySqlExtDAO();
    }

    /**
     * @return KelasSiswaMySqlExtDAO
     */
    public function getKelasSiswaDAO() {
        return new KelasSiswaMySqlExtDAO();
    }

    /**
     * @return KelasStrukturMySqlExtDAO
     */
    public function getKelasStrukturDAO() {
        return new KelasStrukturMySqlExtDAO();
    }

    /**
     * @return KelasTugasMySqlExtDAO
     */
    public function getKelasTugasDAO() {
        return new KelasTugasMySqlExtDAO();
    }

    /**
     * @return LevelGuruMySqlExtDAO
     */
    public function getLevelGuruDAO() {
        return new LevelGuruMySqlExtDAO();
    }

    /**
     * @return LevelKelasMySqlExtDAO
     */
    public function getLevelKelasDAO() {
        return new LevelKelasMySqlExtDAO();
    }

    /**
     * @return LogMySqlExtDAO
     */
    public function getLogDAO() {
        return new LogMySqlExtDAO();
    }

    /**
     * @return LogMateriMySqlExtDAO
     */
    public function getLogMateriDAO() {
        return new LogMateriMySqlExtDAO();
    }

    /**
     * @return LogTugasMySqlExtDAO
     */
    public function getLogTugasDAO() {
        return new LogTugasMySqlExtDAO();
    }

    /**
     * @return LogUjianMySqlExtDAO
     */
    public function getLogUjianDAO() {
        return new LogUjianMySqlExtDAO();
    }

    /**
     * @return LoginAttemptsMySqlExtDAO
     */
    public function getLoginAttemptsDAO() {
        return new LoginAttemptsMySqlExtDAO();
    }

    /**
     * @return MasterEkstraMySqlExtDAO
     */
    public function getMasterEkstraDAO() {
        return new MasterEkstraMySqlExtDAO();
    }

    /**
     * @return MasterGuruMySqlExtDAO
     */
    public function getMasterGuruDAO() {
        return new MasterGuruMySqlExtDAO();
    }

    /**
     * @return MasterHariEfektifMySqlExtDAO
     */
    public function getMasterHariEfektifDAO() {
        return new MasterHariEfektifMySqlExtDAO();
    }

    /**
     * @return MasterJurusanMySqlExtDAO
     */
    public function getMasterJurusanDAO() {
        return new MasterJurusanMySqlExtDAO();
    }

    /**
     * @return MasterKelasMySqlExtDAO
     */
    public function getMasterKelasDAO() {
        return new MasterKelasMySqlExtDAO();
    }

    /**
     * @return MasterMapelMySqlExtDAO
     */
    public function getMasterMapelDAO() {
        return new MasterMapelMySqlExtDAO();
    }

    /**
     * @return MasterSiswaMySqlExtDAO
     */
    public function getMasterSiswaDAO() {
        return new MasterSiswaMySqlExtDAO();
    }

    /**
     * @return MasterSmtMySqlExtDAO
     */
    public function getMasterSmtDAO() {
        return new MasterSmtMySqlExtDAO();
    }

    /**
     * @return MasterTpMySqlExtDAO
     */
    public function getMasterTpDAO() {
        return new MasterTpMySqlExtDAO();
    }

    /**
     * @return PostMySqlExtDAO
     */
    public function getPostDAO() {
        return new PostMySqlExtDAO();
    }

    /**
     * @return PostCommentsMySqlExtDAO
     */
    public function getPostCommentsDAO() {
        return new PostCommentsMySqlExtDAO();
    }

    /**
     * @return PostReplyMySqlExtDAO
     */
    public function getPostReplyDAO() {
        return new PostReplyMySqlExtDAO();
    }

    /**
     * @return RaporAdminSettingMySqlExtDAO
     */
    public function getRaporAdminSettingDAO() {
        return new RaporAdminSettingMySqlExtDAO();
    }

    /**
     * @return RaporCatatanWaliMySqlExtDAO
     */
    public function getRaporCatatanWaliDAO() {
        return new RaporCatatanWaliMySqlExtDAO();
    }

    /**
     * @return RaporDataCatatanMySqlExtDAO
     */
    public function getRaporDataCatatanDAO() {
        return new RaporDataCatatanMySqlExtDAO();
    }

    /**
     * @return RaporDataFisikMySqlExtDAO
     */
    public function getRaporDataFisikDAO() {
        return new RaporDataFisikMySqlExtDAO();
    }

    /**
     * @return RaporDataSikapMySqlExtDAO
     */
    public function getRaporDataSikapDAO() {
        return new RaporDataSikapMySqlExtDAO();
    }

    /**
     * @return RaporFisikMySqlExtDAO
     */
    public function getRaporFisikDAO() {
        return new RaporFisikMySqlExtDAO();
    }

    /**
     * @return RaporKikdMySqlExtDAO
     */
    public function getRaporKikdDAO() {
        return new RaporKikdMySqlExtDAO();
    }

    /**
     * @return RaporKkmMySqlExtDAO
     */
    public function getRaporKkmDAO() {
        return new RaporKkmMySqlExtDAO();
    }

    /**
     * @return RaporNilaiAkhirMySqlExtDAO
     */
    public function getRaporNilaiAkhirDAO() {
        return new RaporNilaiAkhirMySqlExtDAO();
    }

    /**
     * @return RaporNilaiEkstraMySqlExtDAO
     */
    public function getRaporNilaiEkstraDAO() {
        return new RaporNilaiEkstraMySqlExtDAO();
    }

    /**
     * @return RaporNilaiHarianMySqlExtDAO
     */
    public function getRaporNilaiHarianDAO() {
        return new RaporNilaiHarianMySqlExtDAO();
    }

    /**
     * @return RaporNilaiPtsMySqlExtDAO
     */
    public function getRaporNilaiPtsDAO() {
        return new RaporNilaiPtsMySqlExtDAO();
    }

    /**
     * @return RaporNilaiSikapMySqlExtDAO
     */
    public function getRaporNilaiSikapDAO() {
        return new RaporNilaiSikapMySqlExtDAO();
    }

    /**
     * @return RaporPrestasiMySqlExtDAO
     */
    public function getRaporPrestasiDAO() {
        return new RaporPrestasiMySqlExtDAO();
    }

    /**
     * @return RunningTextMySqlExtDAO
     */
    public function getRunningTextDAO() {
        return new RunningTextMySqlExtDAO();
    }

    /**
     * @return SettingMySqlExtDAO
     */
    public function getSettingDAO() {
        return new SettingMySqlExtDAO();
    }

    /**
     * @return UsersMySqlExtDAO
     */
    public function getUsersDAO() {
        return new UsersMySqlExtDAO();
    }

    /**
     * @return UsersGroupsMySqlExtDAO
     */
    public function getUsersGroupsDAO() {
        return new UsersGroupsMySqlExtDAO();
    }

    /**
     * @return UsersProfileMySqlExtDAO
     */
    public function getUsersProfileDAO() {
        return new UsersProfileMySqlExtDAO();
    }


    function getClazzName($tableName){
        $tableName = strtoupper($tableName[0]).substr($tableName,1);
        for($i=0;$i<strlen($tableName);$i++){
            if($tableName[$i]=='_'){
                $tableName = substr($tableName, 0, $i).strtoupper($tableName[$i+1]).substr($tableName, $i+2);
            }
        }
        return $tableName;
    }
}
